name: Open new issue
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "New Issue created from workflow."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
